{% set name = "grimp" %}
{% set version = "2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grimp-{{ version }}.tar.gz
  sha256: 928ae9fe1dfd45e180bca8b3db8ec8003a8d3a23a09d61346b70a47238ac1762

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<3.12
    - pip
  run:
    - python >=3.7,<3.12
    - typing_extensions >=3.10.0.0
#   - networkx >=2.1,<3

test:
  imports:
    - grimp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/grimp/
  summary: Builds a queryable graph of the imports within one or more Python packages.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
